language: node_js
node_js:
- "8.12"
cache:
  directories:
  - ~/.npm
before_script:
- npm install -g npm@latest
- npm install -g expo-cli
script:
- npm ci
- expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
- expo export --public-url https://app.janoticketing.co.uk
deploy:
  provider: pages
  local-dir: dist
  name: Jano Bot
  email: bot@janoticketing.co.uk
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: app.janoticketing.co.uk
  on:
    branch: master
